/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Task } from './task';

export interface TaskRecord {
  task_id?: number;
  task_creator_email?: string;
  task_title?: string;
  task_description?: string;
  task_status?: Task.TaskStatusEnum;
  task_critical?: Task.CriticalEnum;
  task_start_time?: string;
  task_end_time?: string;
}
