/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Member } from './member';

export interface Task { 
    id?: number;
    email?: string;
    title?: string;
    description?: string;
    taskStatus?: Task.TaskStatusEnum;
    critical?: Task.CriticalEnum;
    startTime?: Date;
    endTime?: Date;
    members?: Array<Member>;
}
export namespace Task {
    export type TaskStatusEnum = 'CREATE' | 'POSTPONED' | 'DONE';
    export const TaskStatusEnum = {
        CREATE: 'CREATE' as TaskStatusEnum,
        POSTPONED: 'POSTPONED' as TaskStatusEnum,
        DONE: 'DONE' as TaskStatusEnum
    };
    export type CriticalEnum = 'LOW' | 'NORMAL' | 'HIGH';
    export const CriticalEnum = {
        LOW: 'LOW' as CriticalEnum,
        NORMAL: 'NORMAL' as CriticalEnum,
        HIGH: 'HIGH' as CriticalEnum
    };
}