/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Friend {
  id?: number;
  email?: string;
  status?: Friend.StatusEnum;
  nickName?: string;
}
export namespace Friend {
  export type StatusEnum = 'PENDING' | 'ACCEPTED' | 'SENT';
  export const StatusEnum = {
    PENDING: 'PENDING' as StatusEnum,
    ACCEPTED: 'ACCEPTED' as StatusEnum,
    SENT: 'SENT' as StatusEnum,
  };
}
